### ISSUE TITLE
Can't build saneobj-demo.c (saneobj.c)

### ISSUE THREAD

**Issue by d-mozulyov** [ProgerXP/SaneC#2]
`gcc -o sobj-demo saneobj-demo.c saneobj.c saneex.c`

This code throws so many compiler errors:

> In file included from saneobj-demo.c:2:
> saneobj.h:481:16: warning: declaration does not declare anything
>   481 |     C_vt_(name); \
>       |                ^
> saneobj.h:551:1: note: in expansion of macro ‘classdef’
>   551 | classdef(Object, Object);
>       | ^~~~~~~~
> saneobj.h:486:13: warning: declaration does not declare anything
>   486 |     C_(name); \
>       |             ^
> saneobj.h:551:1: note: in expansion of macro ‘classdef’
>   551 | classdef(Object, Object);
>       | ^~~~~~~~
> saneobj.h:562:13: warning: declaration does not declare anything
>   562 |   Object_vt_;
>       |             ^
> saneobj.h:568:10: warning: declaration does not declare anything
>   568 |   Object_;
>       |          ^
> saneobj.h:481:16: warning: declaration does not declare anything
>   481 |     C_vt_(name); \
>       |                ^
> saneobj.h:572:1: note: in expansion of macro ‘classdef’
>   572 | classdef(Autoref, Object);
>       | ^~~~~~~~
> ...

**Comment by ProgerXP** [comment]
Sorry for late reply.

And sorry that I forgot to mention that you have to use `-fplan9-extensions` with GCC. This is written in the beginning of `saneobj.h` though. I have updated the README.

You should be able to build with `gcc -Wall -Wextra -fplan9-extensions saneobj-demo.c saneobj.c saneex.c` (and `-O3`, optional).
